version: '3'

services:
  lsbengine:
    image: lsbengine:latest
    links:
      - mongo
    env_file:
      - env/docker.env
    volumes:
      - /var/www/assets/images:/opt/docker/images
  
  mongo:
    image: mongo:3.4
    volumes:
      - /data/db:/data/db:Z

  nginx:
    image: my-nginx:latest
    ports:
      - 80:80
      - 443:443
    links:
      - lsbengine
    volumes:
      - /etc/ssl/dhparams:/etc/ssl/dhparams
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/assets/images:/var/www/assets/images
