version: '3'

services:
  lsbengine:
    image: lsbengine:1.0
    links:
      - mongo
    env_file:
      - env/docker.env
    ports:
      - 8080:8080
      - 9090:9090
  
  mongo:
    image: mongo:3.2.4
    volumes:
      - /data/db:/data/db:Z

  nginx:
    image: my-nginx:latest
    ports:
      - 80:80
    links:
      - lsbengine
