version: '3'

services:
  lsbengine:
    image: lsbengine:1.0
    links:
      - mongo
    env_file:
      - env/docker.env
    expose:
      - 9090
      - 8080
    ports:
      - 8080:8080
      - 9090:9090
  
  mongo:
    image: mongo:3.2.4
    volumes:
      - /data/db:/data/db:Z
